spring:
  profiles:
    active: mysql #local local->H2
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3307/springbatch
      username: root
      password: ${DOCKER_MYSQL_PASSWORD}  # 실제 MySQL 비밀번호로 변경
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: true  # false Spring auto start close, JobRunner test
    jdbc:
      initialize-schema: always
